In [1]:
import numpy as np #модуль для работы с матрицами 
import math #модуль для работы с математическими функциями
import random # модуль для генерирования случаных чисел

Решение СЛАУ методом итераций Зейделя

In [23]:

def slauZeidel2(A,b):
    "Принимает матрицу А и столбец b"
    "Возвращает вектор х - решение и количество итераций к"
    eps = 0.01
    n = len(b)
    x = np.zeros(n,'float')
    err = np.copy(b)
    for k in range(100):
        xLast = np.copy(x)
        for i in range(n):
            x[i] = x[i] + (b[i] - np.dot(A[i],x))/A[i,i]
        for i in range(n):
            #err[i] = b[i] - np.dot(A[i],x)
            err[i] = x[i]-xLast[i]
        if np.dot(err,err) < eps**2:
            return x, k
    print("Слишком много шагов")
    return x, k

In [57]:
def slauZeidel(A,b):
    "Принимает матрицу А и столбец b"
    "Алгоритм доработан, матрица приводится к нормальному виду"
    "Возвращает вектор х - решение и количество итераций к"
    eps = 0.01
    n = len(b)
    x = np.zeros(n,'float')
    err = np.copy(b)
    B = np.dot(A.transpose(),A)
    c = np.dot(A.transpose(),b)
    for k in range(1000):
        xLast = np.copy(x)
        for i in range(n):
            x[i] = x[i] + (c[i] - np.dot(B[i],x))/B[i,i]
        for i in range(n):
            err[i] = b[i] - np.dot(A[i],x)
        if np.dot(err,err) < eps**2:
            return x, k
    #print("Слишком много шагов")
    return x, k

In [41]:
x

array([ 0.9394889 ,  0.26518434, -0.35559684,  0.17126165])

In [42]:
np.linalg.solve(A,b)

array([ 0.93601896,  0.26184834, -0.3507109 ,  0.17535545])

In [51]:
def createRandomMatrix(n):
    "генерирует матрицу nxn"
    A = np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            A[i][j] = random.randint(1,10)
    return A
def createRandomVector(n):
    b = np.zeros(n)
    for i in range(n):
        b[i] = random.randint(1,10)
    return b

A = createRandomMatrix(5)#матрица 5x5
b = createRandomVector(5)#столбец 5x1

In [58]:
A

array([[ 1.,  4.,  9.,  5.,  7.],
       [ 3., 10.,  4.,  3.,  2.],
       [ 3.,  4.,  7.,  6., 10.],
       [ 6.,  7., 10.,  8., 10.],
       [ 5.,  3., 10.,  8.,  1.]])

In [59]:
b

array([ 9., 10., 10.,  8.,  3.])

In [60]:
np.linalg.solve(A,b)

array([-2.89292543,  1.35372849, -1.32887189,  3.30210325,  0.27533461])

In [61]:
x,k = slauZeidel(A,b)

In [62]:
x

array([-2.83272248,  1.34270527, -1.27209481,  3.19553238,  0.27991597])