In [6]:
import math
import numpy as np
import random

In [92]:
def findMaxElem(A,n):
    "A - квадратная матрица, n - размер"
    "Возвращает максимальный элемент матриц и  вектор с его индексами"
    max = A[0,1]
    maxIdx = [0,1]
    for i in range(n):
        for j in range(n):
            if i==j:
                continue
            if max < A[i,j]:
                max = A[i,j]
                maxIdx = [i,j]
    return max,maxIdx[0],maxIdx[1]
                
def createRandomMatrix(n):
    "генерирует матрицу nxn"
    A = np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            A[i][j] = random.randint(1,10)
    return A

def createRotateMatrix(n,phi,i,j):
    "Матрица поворота"
    "n - размер квадратной матрицы, phi - угол поворота"
    M = np.eye(n)
    M[i,i] = np.cos(phi)
    M[i,j] = -np.sin(phi)
    M[j,i] = np.sin(phi)
    M[j,j] = np.cos(phi)
    return M

def getPhi(maxElem, aii, ajj):
    "maxElem - максимальный элемент матрицы, в которой мы собираемся его уничтожить"
    phi = 1/2*(np.arctan(2*maxElem/(aii-ajj)))
    return phi

def inverseMatrix(M):
    return np.linalg.inv(M)

def transposeMatrix(M):
    return M.transpose()

In [115]:
def hilbertMatrix(n):
    H = np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            H[i,j] = 1/(i+1+j+1-1)
    return H

In [284]:
def JacobyMethod(M,n):
    "Возвращает собственные числа матрицы М методом Якоби"
    eps = 1.0e-12
    maxElem,i,j = findMaxElem(M,n)
    phi = getPhi(maxElem,i,j)
    R = createRotateMatrix(n,phi,i,j)
    for k in range(10000):
        M = np.dot(np.dot(transposeMatrix(R),M),R)
        maxElem, i , j = findMaxElem(M,n)
        if abs(maxElem) < eps:
            return np.diagonal(M)
        phi = getPhi(maxElem, M[i,i], M[j,j])
        R = createRotateMatrix(n,phi,i,j)
    print("Слишком много итераций")
    return np.diagonal(M)

In [300]:
#Проверка на матрице Гильберта
n=4
H = hilbertMatrix(n)

In [301]:
JacobyMethod(H,n)

array([6.62799777e-02, 1.49929765e+00, 1.10516146e-01, 9.67023040e-05])

In [302]:
H = hilbertMatrix(n)

In [303]:
np.linalg.eigh(H)[0]

array([9.67023040e-05, 6.73827361e-03, 1.69141220e-01, 1.50021428e+00])

In [304]:
#Проверка на произвольной матрице
a = np.array([[3,21,12],
    [21,3,55],
    [12,55,3]])

In [305]:
a

array([[ 3, 21, 12],
       [21,  3, 55],
       [12, 55,  3]])

In [306]:
np.linalg.eigh(a)[0]

array([-52.79596666,  -4.81066517,  66.60663184])

In [307]:
JacobyMethod(a,3)

array([ -4.81066635, -52.79596549,  66.60663184])